import ExcelJS from 'exceljs';
import { SCENARIO, BRANCHES } from '../scenario.js';
import { rng, fitMean, randInt, randFloat, pick, round } from '../lib/num.js';
import { daysInMonth, dayOfMonth, addDays, monthFileTag, monthLabel, isWeekend } from '../lib/dates.js';

/**
 * BaNCS policy admin / workflow extract.
 * Structure: Policy Number, Process Type, Received Date, Completed Date, TAT (days), Status, Branch
 *
 * Distinguishing cues for the classifier: policy-level transactional grain, "Process Type"
 * vocabulary, a per-record TAT column, and a Branch dimension. No aggregation - this is a
 * raw workflow dump, which is exactly what makes it look like a core system extract.
 */

const PROCESS_TO_METRIC = {
  'New Business': 'BANCS_NB_TAT',
  Underwriting: 'BANCS_UW_TAT',
  Claim: 'BANCS_CLAIMS_TAT',
  Endorsement: 'BANCS_ENDORSE_TAT',
};

const SUB_TYPE = {
  'New Business': ['Policy Issuance', 'Policy Issuance - Regular Premium', 'Policy Issuance - Single Premium'],
  Underwriting: ['Medical UW', 'Financial UW', 'Standard UW Decision'],
  Claim: ['Death Claim', 'Critical Illness Claim', 'Income Protection Claim', 'Maturity Claim'],
  Endorsement: ['Address Change', 'Beneficiary Change', 'Premium Frequency Change', 'Sum Assured Alteration'],
};

export async function generateBancs(monthKey, outPath) {
  const sc = SCENARIO[monthKey];
  const r = rng(sc.seed + 11);
  const dim = daysInMonth(monthKey);
  const rows = [];

  for (const [processType, metricId] of Object.entries(PROCESS_TO_METRIC)) {
    const n = sc.volumes.bancs[processType];
    const target = sc.values[metricId];

    // Organic-looking spread, then shifted so the mean lands exactly on the scenario value.
    const raw = Array.from({ length: n }, () => randFloat(r, target * 0.45, target * 1.75));
    const tats = fitMean(raw, target, 1, 0.3);

    for (let i = 0; i < n; i++) {
      // Keep received dates inside the month; late-month items can complete in the next month.
      let received = dayOfMonth(monthKey, randInt(r, 1, dim));
      while (isWeekend(received)) received = addDays(received, 1);
      const completed = addDays(received, Math.max(1, Math.round(tats[i])));
      rows.push({
        policy: `AIBL-${monthKey.slice(0, 4)}-${randInt(r, 100000, 999999)}`,
        processType,
        subType: pick(r, SUB_TYPE[processType]),
        received,
        completed,
        tat: tats[i],
        branch: pick(r, BRANCHES),
        status: 'Completed - STP',
      });
    }
  }

  // Status drives the STP / data-entry accuracy metric:
  //   accuracy % = (total - "Completed - Rework Required") / total
  const reworkCount = sc.volumes.bancs.rework;
  const shuffled = rows.map((v, i) => [r(), i]).sort((a, b) => a[0] - b[0]).map(([, i]) => i);
  shuffled.slice(0, reworkCount).forEach((i) => {
    rows[i].status = 'Completed - Rework Required';
  });
  // A realistic share of the remainder went through with manual touch but no data error.
  shuffled.slice(reworkCount, reworkCount + Math.round(rows.length * 0.28)).forEach((i) => {
    rows[i].status = 'Completed - Manual';
  });

  rows.sort((a, b) => a.received - b.received);

  const wb = new ExcelJS.Workbook();
  wb.creator = 'BaNCS Workflow Reporting';
  wb.created = dayOfMonth(monthKey, dim);

  const ws = wb.addWorksheet('WF_EXTRACT', { views: [{ state: 'frozen', ySplit: 1 }] });
  ws.columns = [
    { header: 'Policy Number', key: 'policy', width: 20 },
    { header: 'Process Type', key: 'processType', width: 16 },
    { header: 'Process Sub Type', key: 'subType', width: 30 },
    { header: 'Received Date', key: 'received', width: 14, style: { numFmt: 'dd/mm/yyyy' } },
    { header: 'Completed Date', key: 'completed', width: 14, style: { numFmt: 'dd/mm/yyyy' } },
    { header: 'TAT (days)', key: 'tat', width: 11, style: { numFmt: '0.0' } },
    { header: 'Status', key: 'status', width: 26 },
    { header: 'Branch', key: 'branch', width: 12 },
  ];
  ws.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  ws.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1F4E79' } };
  ws.getRow(1).alignment = { vertical: 'middle' };
  ws.getRow(1).height = 18;

  rows.forEach((row) => ws.addRow(row));
  ws.autoFilter = { from: 'A1', to: `H${rows.length + 1}` };

  // Second sheet: the run metadata a real core-system export carries.
  const meta = wb.addWorksheet('EXTRACT_INFO');
  meta.columns = [{ width: 26 }, { width: 40 }];
  [
    ['Source System', 'BaNCS Policy Administration'],
    ['Extract ID', `WF-EXT-${monthFileTag(monthKey).toUpperCase()}-01`],
    ['Reporting Period', monthLabel(monthKey)],
    ['Period Start', dayOfMonth(monthKey, 1)],
    ['Period End', dayOfMonth(monthKey, dim)],
    ['Records', rows.length],
    ['Generated By', 'BATCH_RPT_USER'],
    ['Entity', 'AIB Life'],
  ].forEach(([k, v]) => {
    const row = meta.addRow([k, v]);
    row.getCell(1).font = { bold: true };
    if (v instanceof Date) row.getCell(2).numFmt = 'dd/mm/yyyy';
  });

  await wb.xlsx.writeFile(outPath);

  const accuracy = round(((rows.length - reworkCount) / rows.length) * 100, 2);
  return { rows: rows.length, accuracy };
}
