services:
  - type: web
    name: aib-life-proto
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
